# Generated by Django 2.1.2 on 2019-06-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_company_code',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
