# Generated by Django 2.1.2 on 2019-06-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_primary_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_company_pk',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
