# Generated by Django 2.1.2 on 2019-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_primary_company_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_company_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
