# Generated by Django 2.1.2 on 2019-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0003_auto_20190508_1636'),
        ('accounts', '0004_auto_20190521_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='request_form_app.Company'),
        ),
    ]
