# Generated by Django 2.1.2 on 2019-05-30 15:41

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('website', models.URLField()),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('address_line_two', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.TextField(blank=True, max_length=255, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('logo', models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='request_form_app/company_logo', width_field='logo_width')),
                ('logo_height', models.IntegerField(blank=True, null=True)),
                ('logo_width', models.IntegerField(blank=True, null=True)),
                ('company_code', models.TextField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('alternative_email', models.EmailField(blank=True, max_length=256)),
                ('primary_address', models.CharField(blank=True, max_length=256)),
                ('primary_address_line_two', models.CharField(blank=True, max_length=256)),
                ('primary_city', models.CharField(blank=True, max_length=256)),
                ('primary_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('primary_zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('primary_country', models.CharField(blank=True, max_length=256)),
                ('alternative_address', models.CharField(blank=True, max_length=256)),
                ('alternative_address_line_two', models.CharField(blank=True, max_length=256)),
                ('alternative_city', models.CharField(blank=True, max_length=256)),
                ('alternative_state', models.CharField(blank=True, max_length=256)),
                ('alternative_country', models.CharField(blank=True, max_length=256)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=10)),
                ('driver_license_state', models.CharField(blank=True, max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('terms_of_service_signed', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('alternative_phone', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('alternative_phone', models.CharField(blank=True, max_length=13)),
                ('works_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_source', models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('phone', 'Phone'), ('web', 'Web')], default='none', max_length=20)),
                ('website_source', models.URLField(blank=True)),
                ('delete_request', models.CharField(choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5)),
                ('what_request', models.CharField(choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5)),
                ('who_request', models.CharField(choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5)),
                ('opt_out_request', models.CharField(choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('escalated', models.BooleanField(null=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('ready to review', 'Ready for Review'), ('ready for consumer', 'Ready for Consumer'), ('completed', 'Completed'), ('past due', 'Past Due')], default='new', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('alternative_email', models.EmailField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('alternative_phone', models.CharField(blank=True, max_length=13)),
                ('primary_address', models.CharField(blank=True, max_length=256)),
                ('primary_address_line_two', models.CharField(blank=True, max_length=256)),
                ('primary_city', models.CharField(blank=True, max_length=256)),
                ('primary_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('primary_zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('primary_country', models.CharField(blank=True, max_length=256)),
                ('alternative_address', models.CharField(blank=True, max_length=256)),
                ('alternative_address_line_two', models.CharField(blank=True, max_length=256)),
                ('alternative_city', models.CharField(blank=True, max_length=256)),
                ('alternative_state', models.CharField(blank=True, max_length=256)),
                ('alternative_country', models.CharField(blank=True, max_length=256)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=10)),
                ('driver_license_state', models.CharField(blank=True, max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('terms_of_service_signed', models.BooleanField(default=False)),
                ('data_ready_to_send', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='green', max_length=10)),
                ('days_open', models.IntegerField(default='1')),
                ('company_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Consumer')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Contact'),
        ),
    ]
