# Generated by Django 2.1.2 on 2019-03-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_source', models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('phone', 'Phone'), ('web', 'Web')], default='none', max_length=20)),
                ('delete_request', models.BooleanField(null=True)),
                ('what_request', models.BooleanField(null=True)),
                ('who_request', models.BooleanField(null=True)),
                ('opt_out_request', models.BooleanField(null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('escalated', models.BooleanField(null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('past due', 'Past Due')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('alternative_email', models.EmailField(max_length=256)),
                ('primary_address', models.CharField(blank=True, max_length=256)),
                ('primary_address_line_two', models.CharField(blank=True, max_length=256)),
                ('primary_city', models.CharField(blank=True, max_length=256)),
                ('primary_state', models.CharField(blank=True, max_length=256)),
                ('primary_zip', models.CharField(blank=True, max_length=256)),
                ('primary_country', models.CharField(blank=True, max_length=256)),
                ('alternative_address', models.CharField(blank=True, max_length=256)),
                ('alternative_address_line_two', models.CharField(blank=True, max_length=256)),
                ('alternative_city', models.CharField(blank=True, max_length=256)),
                ('alternative_state', models.CharField(blank=True, max_length=256)),
                ('alternative_country', models.CharField(blank=True, max_length=256)),
                ('ssn', models.CharField(blank=True, max_length=9)),
                ('driver_license_number', models.CharField(blank=True, max_length=10)),
                ('driver_license_state', models.CharField(blank=True, max_length=2)),
                ('date_of_birth', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Consumer'),
        ),
    ]
