# Generated by Django 2.1.2 on 2019-05-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0002_auto_20190508_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='request',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
