# Generated by Django 2.1.2 on 2019-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0002_case_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
