# Generated by Django 2.1.2 on 2019-04-10 01:28

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0003_auto_20190409_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='terms_of_service_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='primary_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='primary_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True),
        ),
    ]
