# Generated by Django 2.1.2 on 2019-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0004_auto_20190409_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
