# Generated by Django 2.1.2 on 2019-06-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0004_request_test_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='test_duration',
        ),
    ]
