# Generated by Django 2.1.2 on 2019-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0004_auto_20190521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('ready to review', 'Ready for Review'), ('ready for consumer', 'Ready for Consumer'), ('completed', 'Completed'), ('past due', 'Past Due')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
