# Generated by Django 2.1.2 on 2019-04-13 18:21

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0005_auto_20190413_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('works_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_address_line_two',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='alternative_state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='driver_license_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_address_line_two',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='primary_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='terms_of_service_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='website_source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Consumer'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='company_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company'),
        ),
    ]
