# Generated by Django 2.1.2 on 2019-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0005_remove_request_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='alternative_zip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='request',
            name='data_ready_to_send',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='days_open',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='opt_out_request',
            field=models.CharField(blank=True, choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_source',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('email', 'Email'), ('phone', 'Phone'), ('web', 'Web')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='stage',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in progress', 'In Progress'), ('ready to review', 'Ready for Review'), ('ready for consumer', 'Ready for Consumer'), ('completed', 'Completed'), ('past due', 'Past Due')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='what_request',
            field=models.CharField(blank=True, choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='who_request',
            field=models.CharField(blank=True, choices=[('yes', 'Yes please'), ('no', 'Not right now')], default='no', max_length=5),
        ),
    ]
