# Generated by Django 2.1.2 on 2019-06-19 18:18

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0006_auto_20190617_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='alternative_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
