# Generated by Django 2.1.2 on 2019-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0006_auto_20190413_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
