# Generated by Django 2.1.2 on 2019-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0006_auto_20190524_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='request_form_app/company_logo', width_field='logo_width'),
        ),
    ]
