# Generated by Django 2.1.2 on 2019-06-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0007_consumer_alternative_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(blank=True, max_length=256, unique=True),
        ),
    ]
