# Generated by Django 2.1.2 on 2019-04-14 21:53

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0007_auto_20190413_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='terms_of_service_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='verified_request',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='last_signed_terms_of_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='primary_state',
            field=localflavor.us.models.USStateField(blank=True, default='Alaska', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='primary_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, default=92626, max_length=10),
            preserve_default=False,
        ),
    ]
