# Generated by Django 2.1.2 on 2019-05-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('response_metadata', '0001_initial'),
        ('request_form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_file', models.FileField(upload_to='request_response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
                ('request', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, max_length=255, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('exclude_from_report', models.BooleanField(default=False)),
                ('source_system', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_metadata.Metadata')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request')),
                ('request_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_response.RequestResponse')),
            ],
        ),
    ]
