# Generated by Django 2.1.2 on 2019-05-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_form_app', '0005_auto_20190522_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_file', models.FileField(upload_to='request_response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
                ('request', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request')),
            ],
        ),
    ]
