# Generated by Django 2.1.2 on 2019-05-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company'),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request'),
        ),
    ]
