# Generated by Django 2.1.2 on 2019-06-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request'),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='response_file',
            field=models.FileField(blank=True, upload_to='request_response'),
        ),
    ]
