# Generated by Django 2.1.2 on 2019-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_response', '0002_auto_20190606_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='requestresponse',
            name='sent_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
