# Generated by Django 2.1.2 on 2019-06-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0004_metadatacategory'),
        ('request_form_app', '0005_remove_request_test_duration'),
        ('request_response', '0003_auto_20190606_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_from_report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response_metadata.MetadataCategory')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Request')),
                ('request_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_response.RequestResponse')),
            ],
        ),
    ]
