# Generated by Django 2.1.2 on 2019-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='sequence',
            field=models.IntegerField(blank=True, default='1', max_length=4),
        ),
    ]
