# Generated by Django 2.1.2 on 2019-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data_category',
            field=models.TextField(choices=[('personal', 'Personal Information'), ('commercial', 'Commercial Information'), ('biometric', 'Biometric Information'), ('internet', 'Internet Activity'), ('geolocation', 'Geolocation Information'), ('sensory', 'Sensory Information'), ('psychometric', 'Psychometric Information'), ('employment', 'Employment Information'), ('inferred', 'Inferred Information')], max_length=255),
        ),
    ]
