# Generated by Django 2.1.2 on 2019-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0002_metadata_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='sequence',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
