# Generated by Django 2.1.2 on 2019-05-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0002_auto_20190522_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='company',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
