# Generated by Django 2.1.2 on 2019-06-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_form_app', '0005_remove_request_test_duration'),
        ('response_metadata', '0003_auto_20190606_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=255)),
                ('consumer_label', models.TextField(max_length=255)),
                ('consumer_description', models.TextField(blank=True, max_length=255)),
                ('sequence', models.IntegerField(blank=True, default='1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_form_app.Company')),
            ],
        ),
    ]
