# Generated by Django 2.1.2 on 2019-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_metadata', '0004_metadatacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacategory',
            name='category_type',
            field=models.TextField(choices=[('source', 'Data Source'), ('vendor', '3rd Party'), ('data', 'Data')], default='data', max_length=255),
        ),
    ]
