# Generated by Django 2.1.5 on 2019-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('website', models.URLField(blank=True, max_length=256)),
                ('primary_address', models.CharField(blank=True, max_length=256)),
                ('primary_address_line_two', models.CharField(blank=True, max_length=256)),
                ('primary_city', models.CharField(blank=True, max_length=256)),
                ('primary_state', models.CharField(blank=True, max_length=256)),
                ('primary_zip', models.CharField(blank=True, max_length=256)),
                ('primary_country', models.CharField(blank=True, max_length=256)),
                ('billing_address', models.CharField(blank=True, max_length=256)),
                ('billing_address_line_two', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_state', models.CharField(blank=True, max_length=256)),
                ('billing_zip', models.CharField(blank=True, max_length=256)),
                ('billing_country', models.CharField(blank=True, max_length=256)),
                ('payment_terms', models.CharField(choices=[('7 days', '7 Days'), ('14 days', '14 Days'), ('30 days', '30 Days'), ('60 days', '60 Days')], default='30 days', max_length=10)),
                ('payment_type', models.CharField(choices=[('credit card', 'Credit Card'), ('bank transfer', 'Bank Transfer'), ('direct deposit', 'Direct Deposit'), ('check', 'Check')], default='credit card', max_length=20)),
                ('primary_phone_ext', models.CharField(blank=True, max_length=6)),
                ('active', models.BooleanField()),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('employees', models.CharField(blank=True, max_length=6)),
                ('industry', models.CharField(choices=[('not sure', 'Not Sure'), ('aerospace', 'Aerospace'), ('advertising', 'Advertising'), ('agriculture', 'Agriculture'), ('apparel', 'Apparel'), ('banking', 'Banking'), ('business services', 'Business Services'), ('biotechnology', 'Biotechnology'), ('chemicals', 'Chemicals'), ('communications', 'Communications'), ('consulting', 'Consulting'), ('education', 'Education'), ('electronics', 'Electronics'), ('energy', 'Energy'), ('engineering', 'Engineering'), ('entertainment', 'Entertainment'), ('environmental', 'Environmental'), ('finance', 'Finance'), ('food and beverage', 'Food & Beverage'), ('government', 'Government'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('insurance', 'Insurance'), ('machinary', 'Machinary'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('not for profit', 'Not For Profit'), ('other', 'Other'), ('recreation', 'Recreation'), ('retail', 'Retail'), ('shipping', 'Shipping'), ('technology', 'Technology'), ('telecommunications', 'Telecommunications'), ('transportation', 'Transportation'), ('utilities', 'Utilities')], default='not sure', max_length=50)),
                ('arr', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
